project_id: 779500
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://api.crowdin.com

preserve_hierarchy: true

files:
  # Strings
  - source: /composeApp/src/androidMain/res/values/strings.xml
    translation: /composeApp/src/androidMain/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        es-ES: es
        ga-IE: ga
        he: iw
        id: in
        ml-IN: ml
        pt-PT: pt
        si-LK: si
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        pt-BR: pt-rBR
        sr: b+sr+Cyrl
        sr-CS: b+sr+Latn
  # Plurals
  - source: /composeApp/src/androidMain/res/values/plurals.xml
    translation: /composeApp/src/androidMain/res/values-%android_code%/plurals.xml
    languages_mapping:
      android_code:
        es-ES: es
        ga-IE: ga
        he: iw
        id: in
        ml-IN: ml
        pt-PT: pt
        si-LK: si
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        pt-BR: pt-rBR
        sr: b+sr+Cyrl
        sr-CS: b+sr+Latn
