name: 🐛Bug report
description: Short description of how to trigger this bug
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        <h1 align="center">❗❗ IMPORTANT ❗❗</h1>

        <h2 align="center">PLEASE READ <a
        href='https://kreate.knighthat.me/usr/faq/how-to-make-a-good-issue-ticket'>HOW
        TO MAKE GOOD ISSUE TICKET</a></h1>

        > If your ticket doesn't meet standards mentioned in the article, it'll
        be closed without notice.


        ---
  - type: markdown
    attributes:
      value: >-
        # Please complete the form to the best of your ability


        > In-depth details will reduce bug finding process significantly, it
        gives us more reference to pinpoint the problem.


        Required fields are marked with *

        ---
  - type: input
    id: app-version
    attributes:
      label: Version of Kreate
      description: >-
        [How to get
        it?](https://kreate.knighthat.me/usr/faq/how-to-make-a-good-issue-ticket#version-of-kreate)
      placeholder: v.1.0.0, v.1.1.0, etc.
    validations:
      required: true
  - type: dropdown
    id: android-version
    attributes:
      label: Android version
      description: What version of Android is your phone
      options:
        - 5.0 - 5.1.1 [LOLLIPOP]
        - 6 [M]
        - 7 - 7.1.x  [N]
        - 8 - 8.1 [O]
        - 9 [P]
        - 10 [Q]
        - 11 [R]
        - 12 - 12L [S]
        - 13 [TIRAMISU]
        - 14 [UPSIDE_DOWN_CAKE]
        - 15 [VANILLA_ICE_CREAM]
        - 16 [BAKLAVA]
        - Other
    validations:
      required: true
  - type: input
    id: other-android-version
    attributes:
      label: Other Android version
      description: >-
        Only fill when you select "Other" in Android version, or issue happens
        in multiple versions
      placeholder: '16'
  - type: checkboxes
    id: required-actions
    attributes:
      label: TODOs before submitting a ticket
      description: >-
        Complete these steps fixes most problems, most of the time. Shocker!
        [Why is it
        required?](https://kreate.knighthat.me/usr/faq/how-to-make-a-good-issue-ticket#todos-before-submiting-a-ticket)
      options:
        - label: Update my app to latest version
          required: true
        - label: (If I'm on latest version) Re-install app
          required: true
        - label: I have checked issue page and there's no problem like mine
          required: true
  - type: markdown
    attributes:
      value: >-
        > Please try to complete all of the tasks and not tick them because they
        are required.
  - type: markdown
    attributes:
      value: >
        ---


        # Real questions


        Alright, now we've already applied some of the most common
        troubleshooting steps. Next step is to fill out the description of the
        bug.


        > Remember! More information helps us resolve the problem faster
  - type: textarea
    id: bug-trigger
    attributes:
      label: Tell us how to trigger this bug
      description: 'Each step should be on its own line. You can use simple sentences like:'
      placeholder: 1. Open Kreate 2. Click on A  3. Click on B 4. Boom! Crash happens
    validations:
      required: true
  - type: textarea
    id: video
    attributes:
      label: Submit a video
      description: >-
        Don't know how? [Here's the
        instructions](https://kreate.knighthat.me/usr/faq/how-to-make-a-good-issue-ticket#tell-us-how-to-trigger-this-bug).
      placeholder: 'Please record a short clip of the bug, it helps tremendously. '
  - type: textarea
    id: log
    attributes:
      label: Logs
      description: >-
        Instructions on how to extract logs can be found
        [here](https://kreate.knighthat.me/usr/faq/how-to-make-a-good-issue-ticket#logs).
      value: |-
        <details>
          <summary>Logs</summary>

          [If you have multiple logs, please copy "details" for each log, name them appropriately, make sure they are different from each other]

          <Paste your log here>
        </details>
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
